```{r echo=FALSE}
library(readr)
library(ggplot2)
library(dplyr)
library(tidymodels)
library(rjson)
library(stringr)
library(broom)
library(data.table)
tidymodels_prefer()
```

# load in data
```{r}
stringency_data <- read.csv('covid-stringency-index.csv')
all_data <- read.csv('owid-covid-data.csv')

isl_swe_data <- all_data %>%
  filter(iso_code=="SWE"|iso_code=='ISL')

what_questions_are = read.csv(file = 'what_questsions_are.csv')
what_answer_codes_mean = read.csv(file = 'what_answer_codes_mean.csv')
country_code_data = read.csv(file = "country_code_data.csv")
mean_data = fromJSON(file="mean_data_per_country.json")
get_full_name <- function(abv) {
  to_ret <- (country_code_data %>% filter(Code==abv))$Name
  return(to_ret)
}

#data_index = fromJSON(file='data_index_orient.json')
data_index = fromJSON(file='data_with_dates.json')
```

# setup variables
```{r}
countries = c('SE','IT','UK','US','AU','DE','ES','MX','JP','KR','CN')
country = 'IT'
quest = 'FinitePool_2'
fear_questions = c('CanadaQ_2', 'CanadaQ_1', 'Longitude_2', 'Friends_8', 'Personal_8')
#fear_questions = c('FinitePool_2')
controlling_for_questions = c('COVIDeffect_4', 'COVIDeffect_1')
country_full_name = (country_code_data %>% filter(Code==country))$Name
```

# helper functions
```{r}
put_new_lines <- function(string, num_chars) {
  if (nchar(string) <= num_chars) {
    return(string)
  }
  for (i in num_chars:nchar(string)) {
    if (substr(string,i,i) == " ") {
      first = substr(string, 1, i)
      last = substr(string, i+1, nchar(string))
      if (nchar(last) >= num_chars) {
        last = put_new_lines(last, num_chars)
      }
      new_string <- paste(first, "\n", last)
      return(new_string)
    }
  }
  return(string)
}

normalit<-function(m){
   (m - min(m))/(max(m)-min(m))
}

aggregate_data_func <- function(df) {
  aggregate_data <- data.frame(matrix(ncol = length(df), nrow = 11))
  colnames(aggregate_data) <- df
  
  for (question in df) {
    #print(question)
    d1 <- mean_data[[question]] %>%
      data.frame()
    d1 <- data.frame(country=names(d1),Average=t(d1)) %>%
      mutate(country = gsub(".", " ", country, fixed=TRUE)) %>%
      mutate(stringency = as.numeric(mean_data$stringnecy)) %>%
      mutate(Average = normalit(Average))
    d1[question] = normalit(d1$Average)
    
    if (nrow(aggregate_data) == 0) {
      aggregate_data <- d1
    } else {
      aggregate_data <- merge(d1, aggregate_data, all=TRUE)
    }
  }
  return(aggregate_data)
}

compress_df <- function(df) {
  temp <- df %>%
    select(-Average, -stringency)
  stringency_data <- df %>%
    select(country, stringency, 3) %>%
    distinct() %>%
    na.omit()
  compressed_data <- setDT(temp)[, lapply(.SD, na.omit), by = country] %>%
    mutate(stringency = stringency_data$stringency)
  return(compressed_data)
}
```

# setup helper variables
```{r}
question_text <- what_questions_are %>%
  filter(var==quest) %>%
  select('question')

code_text <- what_answer_codes_mean %>%
  filter(var==quest) %>%
  select('code', 'label')

labels = vector()
to_paste <- ""
for (i in 1:max(code_text$code)){
  to_paste = if (i%%2) "" else "\n \n"
  if (i %in% code_text$code) {
    labels <- c(labels, paste(to_paste,put_new_lines(code_text[code_text$code==i,]$label,13)))
  } else {
    labels <- c(labels, i)
  }
}
```

# single histogram plot with question and country
```{r}
to_plot <- data_index[[quest]][[country]] %>%
  as.numeric() %>%
  data.frame()

to_plot$lab <- code_text$label[match(to_plot$.,code_text$code)]

title <- put_new_lines(question_text[question_text != "",], 76)

to_plot%>%
  ggplot(aes(x=.))+
    stat_count() +
    scale_x_discrete(limits=labels,labels=labels) +
    labs(title=title)
```

# setup stringency with all countries
```{r}
question_text <- what_questions_are %>%
  filter(var==quest) %>%
  select('question')

#question_text <- paste("\"", question_text[question_text != "",], sep = "") %>%
#  paste("\" vs stringency per country", sep = "")
#title <- put_new_lines(question_text,76)

title <- put_new_lines('Fear of Covid vs Stringency of country policies',76)

aggregate_data <- aggregate_data_func(fear_questions)
compressed_data <- compress_df(aggregate_data)

```


# plot question with all countries against stringency
``` {r}
aggregate_data %>%
  ggplot(aes(y=Average, x=stringency, color=country)) +
    geom_point() +
    labs(title=title, x="Stringency", y="Average Fear per Question")
```

# regression with question and stringency with all countries
```{r}

fear_scores <- aggregate(Average ~ country, aggregate_data, mean)
regression_data <- merge(compress_df(aggregate_data_func(controlling_for_questions)), fear_scores) %>%
  mutate(fear_index = Average) %>%
  select(-Average) %>%
  filter(country != 'Mexico')

lm_spec <-
    linear_reg() %>% 
    set_engine(engine = 'lm') %>% 
    set_mode('regression')

mod <- fit(lm_spec,
            #fear_index ~ stringency_sq +stringency,
            fear_index ~ . -country,
            data = regression_data)

mod %>%
  tidy()

regression_data %>%
  select(-country) %>%
  ggplot(aes(x=stringency, y=fear_index)) +
  geom_point() +
  geom_smooth(se=FALSE) +
  labs(x = "Covid-19 Policy Stringency", y="Average Composite Fear Score", title="Fear of Covid-19 vs Stringency of Covid-19 Policy")
  geom_smooth(method="lm", level=0.90, formula = y ~ x)
```

# doing stuff with individual data
```{r}
# we want to model fear by the media and government influence questions

person_data = read.csv('person_dat.csv')
person_data <- person_data %>%
  mutate(govTrust = govtrustQ1,
         media_trust = journalisttrustQ1,
         fear = FinitePool_2,
         personal_exp = COVIDeffect_1,
         loved_one_exp = COVIDeffect_4) %>%
  select(media_trust, fear, personal_exp, loved_one_exp) %>%
  na.omit()

lm_spec <-
    linear_reg() %>% 
    set_engine(engine = 'lm') %>% 
    set_mode('regression')

mod <- fit(lm_spec,
            fear ~ .,
            data = person_data)

mod %>%
  tidy()

person_data %>%
  select(media_trust, fear) %>%
  ggplot(aes(x=as.factor(media_trust), y=fear)) +
  geom_boxplot() +
  labs(x=put_new_lines("Thinking about the coronavirus/COVID-19 information: how much did you trust the information from journalists and commentators in the media?",75), y="Composite Fear Score", title="Fear of Covid-19 vs Trust in Media")
```

